### ISSUE TITLE
TODO Markus

### ISSUE THREAD

**Issue by WSSMRKS** [WSSMRKS/42_minishell#98]
- [x] Solve last issues with Signals (echo not working after SIGINT)
- [x] echo $? not working anymore. redo changing source of exitstatus from g_signal to last_ret.
- [x] SIGINT not working in several instances of minishell.
